############################################################
all: 	help

help:           
	@echo "make {lib|clean|help}"
	@echo " "
	@echo "   lib - compile libraries"
	@echo " "
	@echo "   clean - clean the package"
	@echo "   help  - print this message"
	@echo " "

lib:
	+cd aniTET && make lib
	+cd aniFRT && make lib

clean: 
	+cd aniTET && make clean
	+cd aniFRT && make clean

purge: 
	+cd aniTET && make purge
	+cd aniFRT && make purge

