############################################################
all: 	lib exe

lib:
	+cd SCG && make lib

exe:
	+cd CAD && make exe
	+cd SCG && make exe

clean: 
	+cd CAD && make clean
	+cd SCG && make clean

purge: 
	+cd CAD && make purge
	+cd SCG && make purge
