############################################################
all: 	lib

lib:
	+cd PRM && make lib
	+cd MDF && make lib
	+cd CAD && make lib
	+cd SCG && make lib

clean: 
	+cd PRM && make clean
	+cd MDF && make clean
	+cd CAD && make clean
	+cd SCG && make clean
	+cd GUI && make clean

purge: 
	+cd PRM && make purge
	+cd MDF && make purge
	+cd CAD && make purge
	+cd SCG && make purge
	+cd GUI && make purge

