############################################################
all: 	exe

ifdef CASROOT
exe:
	@echo Please use OpenCASCADE gui \(DRAWEXE\)
else
exe:
	@echo CASROOT is unset, OpenCASCADE support is disabled
endif

lib:

clean: 

purge:
